#!/usr/bin/env sh
#
# This is a helper script used to only invoke a single tox environment.
# Solely used for a quick way to run a supported environment without
# having to try to form one on the command line.

exec tox -e py312-sphinx73 $@
