# SPDX-License-Identifier: BSD-2-Clause
# Copyright Sphinx Confluence Builder Contributors (AUTHORS)

from tests.lib.parse import parse
from tests.lib.testcase import ConfluenceTestCase
from tests.lib.testcase import setup_builder


class TestConfluenceSinglepageToctree(ConfluenceTestCase):
    @setup_builder('singleconfluence')
    def test_storage_singlepage_docref_pageref(self):
        dataset = self.datasets / 'singlepage-docref'

        out_dir = self.build(dataset)

        with parse('index', out_dir) as data:
            links = data.find_all('ac:link')
            self.assertEqual(len(links), 1)

            # the anchor value should be pointing to `pageb2`, which maps to the
            # anchor target generated by confluence based on the title/heading
            # being given a value of "pageb2" (opposed to just `pageb` which is
            # a raw map to the docname target)
            link = links[0]
            self.assertIsNotNone(link)
            self.assertTrue(link.has_attr('ac:anchor'))
            self.assertEqual(link['ac:anchor'], 'pageb2')

    @setup_builder('singleconfluence')
    def test_storage_singlepage_docref_index_no_title(self):
        dataset = self.datasets / 'singlepage-docref'

        out_dir = self.build(dataset)

        with parse('index', out_dir) as data:
            links = data.find_all('a')
            self.assertEqual(len(links), 1)

            # link from pagea to the index should have been replaced with a #top
            link = links[0]
            self.assertIsNotNone(link)
            self.assertTrue(link.has_attr('href'))
            self.assertEqual(link['href'], '#top')

    @setup_builder('singleconfluence')
    def test_storage_singlepage_docref_index_with_title(self):
        config = dict(self.config)
        config['confluence_remove_title'] = False

        dataset = self.datasets / 'singlepage-docref'

        out_dir = self.build(dataset, config=config)

        with parse('index', out_dir) as data:
            links = data.find_all('ac:link')
            self.assertEqual(len(links), 2)

            # the anchor value should be pointing to `index2`, which maps to the
            # anchor target generated by confluence based on the title/heading
            # being given a value of "index2" (opposed to just `index` which is
            # a raw map to the docname target)
            link = links[1]  # (second link)
            self.assertIsNotNone(link)
            self.assertTrue(link.has_attr('ac:anchor'))
            self.assertEqual(link['ac:anchor'], 'index2')
